name: UI Garden Build Checks
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  react-app-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: npm i
        run: npm i
      - name: test
        run: npm run test
      - name: lint (Prettier + ESLint)
        run: npm run lint
      - name: format (Prettier write + ESLint fix)
        run: npm run format
      - name: test
        run: npm run test
      - name: build
        run: npm run build
